/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author Usuario
 */
public class GestionAutores extends javax.swing.JFrame {

    /**
     * Creates new form GestionAutores
     */
    public GestionAutores() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtPaisAutor = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtxtIdAutor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtxtEdadAutor = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtblMostrarAutor = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jtxtNombreAutor1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jbtnMostrarAutor = new javax.swing.JButton();
        jbtnGuardarAutor = new javax.swing.JButton();
        jbtnActualizarAutor = new javax.swing.JButton();
        jbtnEliminarAutor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        btnSalira = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setLayout(new java.awt.BorderLayout());

        jButton1.setBackground(new java.awt.Color(51, 102, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LIBROOOOOOASA.png"))); // NOI18N
        jButton1.setText("Libros");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 170, 40));

        jPanel4.setLayout(new java.awt.BorderLayout());

        jButton7.setBackground(new java.awt.Color(51, 102, 255));
        jButton7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Autores.png"))); // NOI18N
        jButton7.setText("Autores");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 170, 40));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Autores.png"))); // NOI18N
        jLabel1.setText("Gestion de Autores");
        jPanel6.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 250, 50));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Nacionalidad:");
        jPanel6.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 100, 30));

        jtxtPaisAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtPaisAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtPaisAutorActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtPaisAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 240, 170, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Id.Autor:");
        jPanel6.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, 30));

        jtxtIdAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtIdAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtIdAutorActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtIdAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 170, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Edad:");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 40, 30));

        jtxtEdadAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtEdadAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtEdadAutorActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtEdadAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 170, 40));

        jtblMostrarAutor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtblMostrarAutor);

        jPanel6.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 60, 300, 250));

        jPanel5.setBackground(new java.awt.Color(255, 255, 51));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 760, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 50, Short.MAX_VALUE)
        );

        jPanel6.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 50));

        jtxtNombreAutor1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jtxtNombreAutor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtNombreAutor1ActionPerformed(evt);
            }
        });
        jPanel6.add(jtxtNombreAutor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 170, 40));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setText("Nombre :  ");
        jPanel6.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, 30));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 760, 320));

        jbtnMostrarAutor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jbtnMostrarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Mostrar.png"))); // NOI18N
        jbtnMostrarAutor.setText("Mostrar");
        jbtnMostrarAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jbtnMostrarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 450, 150, 50));

        jbtnGuardarAutor.setBackground(new java.awt.Color(51, 102, 255));
        jbtnGuardarAutor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jbtnGuardarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Guardar.png"))); // NOI18N
        jbtnGuardarAutor.setText("Guardar");
        jbtnGuardarAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jbtnGuardarAutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnGuardarAutorActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnGuardarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 150, 50));

        jbtnActualizarAutor.setBackground(new java.awt.Color(153, 255, 102));
        jbtnActualizarAutor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jbtnActualizarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Actualizar.png"))); // NOI18N
        jbtnActualizarAutor.setText("Actualizar");
        jbtnActualizarAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jbtnActualizarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 450, 160, 50));

        jbtnEliminarAutor.setBackground(new java.awt.Color(255, 51, 51));
        jbtnEliminarAutor.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jbtnEliminarAutor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Eliminar.png"))); // NOI18N
        jbtnEliminarAutor.setText("Eliminar");
        jbtnEliminarAutor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.add(jbtnEliminarAutor, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 150, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/LOGODECOLEGIO.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, -10, 230, 170));

        jButton2.setBackground(new java.awt.Color(51, 102, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/editorial.png"))); // NOI18N
        jButton2.setText("Editorial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 170, 40));

        btnSalira.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        btnSalira.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/salirasdas.png"))); // NOI18N
        btnSalira.setText("Salir");
        btnSalira.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnSalira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaliraActionPerformed(evt);
            }
        });
        jPanel2.add(btnSalira, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 200, 130, 60));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 940, 530));

        jPanel1.setBackground(new java.awt.Color(255, 51, 51));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 990, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 590, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-4, -4, 990, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         Gestion newframe = new Gestion();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jtxtPaisAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtPaisAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtPaisAutorActionPerformed

    private void jtxtIdAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtIdAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtIdAutorActionPerformed

    private void jtxtEdadAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtEdadAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtEdadAutorActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        GestionEditorial newframe = new GestionEditorial();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSaliraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaliraActionPerformed
        MenuAdmin newframe = new MenuAdmin ();
        newframe.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSaliraActionPerformed

    private void jtxtNombreAutor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtNombreAutor1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxtNombreAutor1ActionPerformed

    private void jbtnGuardarAutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnGuardarAutorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtnGuardarAutorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionAutores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionAutores().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnSalira;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtnActualizarAutor;
    public javax.swing.JButton jbtnEliminarAutor;
    public javax.swing.JButton jbtnGuardarAutor;
    public javax.swing.JButton jbtnMostrarAutor;
    public javax.swing.JTable jtblMostrarAutor;
    public javax.swing.JTextField jtxtEdadAutor;
    public javax.swing.JTextField jtxtIdAutor;
    public javax.swing.JTextField jtxtNombreAutor1;
    public javax.swing.JTextField jtxtPaisAutor;
    // End of variables declaration//GEN-END:variables
}
